### PR TITLE
display contest DateTime configuration in client's timezone

### PR DESCRIPTION
**Pull request by ivanhendrajaya**
fix bug and improve error message in contest DateTime configuration
improve input DateTime view
move datetimepicker to play-commons

part of ia-toki/judgels#128

### CODE REVIEW

**Comment by fushar** [comment]
Sorry for late response.

This pull request is not up-to-date. Please use the new formatISOUTCDateTime() in JudgelUtils.

**Comment by fushar** [comment]
(Just fix, commit, and push to this branch.)

**Comment by ivanhendrajaya** [comment]
Please look at this pull request ia-toki/judgels-play-commons#8.

**Comment by fushar** [comment]
Yes, ignore my previous messages.

**Comment by fushar** [comment]
Merged as 558861292b4152ef3fa77ff858446d6790672f00.

**Pull request closed without merging**
